'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace SapSOAPin4
    
    'CODEGEN: L'elemento di estensione WSDL facoltativo 'Policy' dallo spazio dei nomi 'http://schemas.xmlsoap.org/ws/2004/09/policy' non è stato gestito.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_MES_INBOUND_4_B", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZWS_MES_INBOUND_4
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZmesWsIn4OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SAPReader.My.MySettings.Default.SAPReader_SapSOAPin4_ZWS_MES_INBOUND_4
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZmesWsIn4Completed As ZmesWsIn4CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_MES_INBOUND_4:ZmesWsIn4Reque"& _ 
            "st", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZmesWsIn4(<System.Xml.Serialization.XmlElementAttribute("ZmesWsIn4", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZmesWsIn41 As ZmesWsIn4) As <System.Xml.Serialization.XmlElementAttribute("ZmesWsIn4Response", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZmesWsIn4Response
            Dim results() As Object = Me.Invoke("ZmesWsIn4", New Object() {ZmesWsIn41})
            Return CType(results(0),ZmesWsIn4Response)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZmesWsIn4Async(ByVal ZmesWsIn41 As ZmesWsIn4)
            Me.ZmesWsIn4Async(ZmesWsIn41, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZmesWsIn4Async(ByVal ZmesWsIn41 As ZmesWsIn4, ByVal userState As Object)
            If (Me.ZmesWsIn4OperationCompleted Is Nothing) Then
                Me.ZmesWsIn4OperationCompleted = AddressOf Me.OnZmesWsIn4OperationCompleted
            End If
            Me.InvokeAsync("ZmesWsIn4", New Object() {ZmesWsIn41}, Me.ZmesWsIn4OperationCompleted, userState)
        End Sub
        
        Private Sub OnZmesWsIn4OperationCompleted(ByVal arg As Object)
            If (Not (Me.ZmesWsIn4CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZmesWsIn4Completed(Me, New ZmesWsIn4CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZmesWsIn4
        
        Private iArticoloField As String
        
        Private iIdEventoField As String
        
        Private iTipoElaborazioneField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IArticolo() As String
            Get
                Return Me.iArticoloField
            End Get
            Set
                Me.iArticoloField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IIdEvento() As String
            Get
                Return Me.iIdEventoField
            End Get
            Set
                Me.iIdEventoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITipoElaborazione() As String
            Get
                Return Me.iTipoElaborazioneField
            End Get
            Set
                Me.iTipoElaborazioneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZmesTrPianif
        
        Private itemField As String
        
        Private colourField As String
        
        Private typeTraceField As String
        
        Private qMulField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Colour() As String
            Get
                Return Me.colourField
            End Get
            Set
                Me.colourField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TypeTrace() As String
            Get
                Return Me.typeTraceField
            End Get
            Set
                Me.typeTraceField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property QMul() As Decimal
            Get
                Return Me.qMulField
            End Get
            Set
                Me.qMulField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZmesWsIn4Response
        
        Private eAnagrArticPianifField() As ZmesTrPianif
        
        Private eMessageField As String
        
        Private eRetcodeField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property EAnagrArticPianif() As ZmesTrPianif()
            Get
                Return Me.eAnagrArticPianifField
            End Get
            Set
                Me.eAnagrArticPianifField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EMessage() As String
            Get
                Return Me.eMessageField
            End Get
            Set
                Me.eMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ERetcode() As Integer
            Get
                Return Me.eRetcodeField
            End Get
            Set
                Me.eRetcodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ZmesWsIn4CompletedEventHandler(ByVal sender As Object, ByVal e As ZmesWsIn4CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZmesWsIn4CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZmesWsIn4Response
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZmesWsIn4Response)
            End Get
        End Property
    End Class
End Namespace
