'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace SapSOAPin2
    
    'CODEGEN: L'elemento di estensione WSDL facoltativo 'Policy' dallo spazio dei nomi 'http://schemas.xmlsoap.org/ws/2004/09/policy' non è stato gestito.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_MES_INBOUND_2_B", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZWS_MES_INBOUND_2
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZmesWsIn2OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SAPReader.My.MySettings.Default.SAPReader_SapSOAPin2_ZWS_MES_INBOUND_2
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZmesWsIn2Completed As ZmesWsIn2CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:soap:functions:mc-style:ZWS_MES_INBOUND_2:ZmesWsIn2Reque"& _ 
            "st", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZmesWsIn2(<System.Xml.Serialization.XmlElementAttribute("ZmesWsIn2", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ByVal ZmesWsIn21 As ZmesWsIn2) As <System.Xml.Serialization.XmlElementAttribute("ZmesWsIn2Response", [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")> ZmesWsIn2Response
            Dim results() As Object = Me.Invoke("ZmesWsIn2", New Object() {ZmesWsIn21})
            Return CType(results(0),ZmesWsIn2Response)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZmesWsIn2Async(ByVal ZmesWsIn21 As ZmesWsIn2)
            Me.ZmesWsIn2Async(ZmesWsIn21, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZmesWsIn2Async(ByVal ZmesWsIn21 As ZmesWsIn2, ByVal userState As Object)
            If (Me.ZmesWsIn2OperationCompleted Is Nothing) Then
                Me.ZmesWsIn2OperationCompleted = AddressOf Me.OnZmesWsIn2OperationCompleted
            End If
            Me.InvokeAsync("ZmesWsIn2", New Object() {ZmesWsIn21}, Me.ZmesWsIn2OperationCompleted, userState)
        End Sub
        
        Private Sub OnZmesWsIn2OperationCompleted(ByVal arg As Object)
            If (Not (Me.ZmesWsIn2CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZmesWsIn2Completed(Me, New ZmesWsIn2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZmesWsIn2
        
        Private iIdEventoField As String
        
        Private iTipoElaborazioneField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IIdEvento() As String
            Get
                Return Me.iIdEventoField
            End Get
            Set
                Me.iIdEventoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITipoElaborazione() As String
            Get
                Return Me.iTipoElaborazioneField
            End Get
            Set
                Me.iTipoElaborazioneField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:soap:functions:mc-style")>  _
    Partial Public Class ZmesWsIn2Response
        
        Private eMessageField As String
        
        Private eRetcodeField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property EMessage() As String
            Get
                Return Me.eMessageField
            End Get
            Set
                Me.eMessageField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ERetcode() As Integer
            Get
                Return Me.eRetcodeField
            End Get
            Set
                Me.eRetcodeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ZmesWsIn2CompletedEventHandler(ByVal sender As Object, ByVal e As ZmesWsIn2CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZmesWsIn2CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZmesWsIn2Response
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZmesWsIn2Response)
            End Get
        End Property
    End Class
End Namespace
