'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace SAPSOAPin5
    
    'CODEGEN: L'elemento di estensione WSDL facoltativo 'Policy' dallo spazio dei nomi 'http://schemas.xmlsoap.org/ws/2004/09/policy' non è stato gestito.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_MES_INBOUND_5_B", [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZWS_MES_INBOUND_5
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZmesWsIn5OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SAPReader.My.MySettings.Default.SAPReader_SAPSOAPin5_ZWS_MES_INBOUND_5
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZmesWsIn5Completed As ZmesWsIn5CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZWS_MES_INBOUND_5:ZmesWsIn5Request", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZmesWsIn5(<System.Xml.Serialization.XmlElementAttribute("ZmesWsIn5", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ByVal ZmesWsIn51 As ZmesWsIn5) As <System.Xml.Serialization.XmlElementAttribute("ZmesWsIn5Response", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ZmesWsIn5Response
            Dim results() As Object = Me.Invoke("ZmesWsIn5", New Object() {ZmesWsIn51})
            Return CType(results(0),ZmesWsIn5Response)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZmesWsIn5Async(ByVal ZmesWsIn51 As ZmesWsIn5)
            Me.ZmesWsIn5Async(ZmesWsIn51, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZmesWsIn5Async(ByVal ZmesWsIn51 As ZmesWsIn5, ByVal userState As Object)
            If (Me.ZmesWsIn5OperationCompleted Is Nothing) Then
                Me.ZmesWsIn5OperationCompleted = AddressOf Me.OnZmesWsIn5OperationCompleted
            End If
            Me.InvokeAsync("ZmesWsIn5", New Object() {ZmesWsIn51}, Me.ZmesWsIn5OperationCompleted, userState)
        End Sub
        
        Private Sub OnZmesWsIn5OperationCompleted(ByVal arg As Object)
            If (Not (Me.ZmesWsIn5CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZmesWsIn5Completed(Me, New ZmesWsIn5CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZmesWsIn5
        
        Private i_ARTICOLOField As String
        
        Private i_ID_EVENTOField As String
        
        Private i_TIPO_ELABORAZIONEField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property I_ARTICOLO() As String
            Get
                Return Me.i_ARTICOLOField
            End Get
            Set
                Me.i_ARTICOLOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property I_ID_EVENTO() As String
            Get
                Return Me.i_ID_EVENTOField
            End Get
            Set
                Me.i_ID_EVENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property I_TIPO_ELABORAZIONE() As String
            Get
                Return Me.i_TIPO_ELABORAZIONEField
            End Get
            Set
                Me.i_TIPO_ELABORAZIONEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_DISRIC
        
        Private zPADREField As String
        
        Private zFIGLIOField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZPADRE() As String
            Get
                Return Me.zPADREField
            End Get
            Set
                Me.zPADREField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZFIGLIO() As String
            Get
                Return Me.zFIGLIOField
            End Get
            Set
                Me.zFIGLIOField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZmesWsIn5Response
        
        Private e_DISTINTA_RICField() As ZMES_TR_DISRIC
        
        Private e_MESSAGEField As String
        
        Private e_RETCODEField As Integer
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_DISTINTA_RIC() As ZMES_TR_DISRIC()
            Get
                Return Me.e_DISTINTA_RICField
            End Get
            Set
                Me.e_DISTINTA_RICField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property E_MESSAGE() As String
            Get
                Return Me.e_MESSAGEField
            End Get
            Set
                Me.e_MESSAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property E_RETCODE() As Integer
            Get
                Return Me.e_RETCODEField
            End Get
            Set
                Me.e_RETCODEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ZmesWsIn5CompletedEventHandler(ByVal sender As Object, ByVal e As ZmesWsIn5CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZmesWsIn5CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZmesWsIn5Response
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZmesWsIn5Response)
            End Get
        End Property
    End Class
End Namespace
