'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Il codice sorgente è stato generato automaticamente da Microsoft.VSDesigner, versione 4.0.30319.42000.
'
Namespace SapSOAPin
    
    'CODEGEN: L'elemento di estensione WSDL facoltativo 'Policy' dallo spazio dei nomi 'http://schemas.xmlsoap.org/ws/2004/09/policy' non è stato gestito.
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="ZWS_MES_INBOUND_1_B", [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZWS_MES_INBOUND_1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ZMES_WS_INOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.SAPReader.My.MySettings.Default.SAPReader_SapSOAPin_ZWS_MES_INBOUND_1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ZMES_WS_INCompleted As ZMES_WS_INCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sap-com:document:sap:rfc:functions:ZWS_MES_INBOUND_1:ZMES_WS_INRequest", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function ZMES_WS_IN(<System.Xml.Serialization.XmlElementAttribute("ZMES_WS_IN", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ByVal ZMES_WS_IN1 As ZMES_WS_IN) As <System.Xml.Serialization.XmlElementAttribute("ZMES_WS_INResponse", [Namespace]:="urn:sap-com:document:sap:rfc:functions")> ZMES_WS_INResponse
            Dim results() As Object = Me.Invoke("ZMES_WS_IN", New Object() {ZMES_WS_IN1})
            Return CType(results(0),ZMES_WS_INResponse)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ZMES_WS_INAsync(ByVal ZMES_WS_IN1 As ZMES_WS_IN)
            Me.ZMES_WS_INAsync(ZMES_WS_IN1, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ZMES_WS_INAsync(ByVal ZMES_WS_IN1 As ZMES_WS_IN, ByVal userState As Object)
            If (Me.ZMES_WS_INOperationCompleted Is Nothing) Then
                Me.ZMES_WS_INOperationCompleted = AddressOf Me.OnZMES_WS_INOperationCompleted
            End If
            Me.InvokeAsync("ZMES_WS_IN", New Object() {ZMES_WS_IN1}, Me.ZMES_WS_INOperationCompleted, userState)
        End Sub
        
        Private Sub OnZMES_WS_INOperationCompleted(ByVal arg As Object)
            If (Not (Me.ZMES_WS_INCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ZMES_WS_INCompleted(Me, New ZMES_WS_INCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_WS_IN
        
        Private i_ARTICOLOField As String
        
        Private i_DATA_SCHEMA_ELEField As String
        
        Private i_ID_EVENTOField As String
        
        Private i_ORDINE_PRODUZIONEField As String
        
        Private i_TIPO_ELABORAZIONEField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property I_ARTICOLO() As String
            Get
                Return Me.i_ARTICOLOField
            End Get
            Set
                Me.i_ARTICOLOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property I_DATA_SCHEMA_ELE() As String
            Get
                Return Me.i_DATA_SCHEMA_ELEField
            End Get
            Set
                Me.i_DATA_SCHEMA_ELEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property I_ID_EVENTO() As String
            Get
                Return Me.i_ID_EVENTOField
            End Get
            Set
                Me.i_ID_EVENTOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property I_ORDINE_PRODUZIONE() As String
            Get
                Return Me.i_ORDINE_PRODUZIONEField
            End Get
            Set
                Me.i_ORDINE_PRODUZIONEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property I_TIPO_ELABORAZIONE() As String
            Get
                Return Me.i_TIPO_ELABORAZIONEField
            End Get
            Set
                Me.i_TIPO_ELABORAZIONEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_TESTATA_ODP_INTERNA
        
        Private n_ORDER_MFGField As String
        
        Private sTATUSField As String
        
        Private tYPE_ORDERField As String
        
        Private iTEMField As String
        
        Private cOLOURField As String
        
        Private q_PLANNEDField As Decimal
        
        Private q_PRODUCEDField As Decimal
        
        Private tYPE_BOXField As String
        
        Private dATE_BEGINField As String
        
        Private dATE_ENDField As String
        
        Private dATE_BEGIN_REALField As String
        
        Private dATE_END_REALField As String
        
        Private dESCRIPTION_ADDField As String
        
        Private n_LISTField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_ORDER_MFG() As String
            Get
                Return Me.n_ORDER_MFGField
            End Get
            Set
                Me.n_ORDER_MFGField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property STATUS() As String
            Get
                Return Me.sTATUSField
            End Get
            Set
                Me.sTATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TYPE_ORDER() As String
            Get
                Return Me.tYPE_ORDERField
            End Get
            Set
                Me.tYPE_ORDERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM() As String
            Get
                Return Me.iTEMField
            End Get
            Set
                Me.iTEMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COLOUR() As String
            Get
                Return Me.cOLOURField
            End Get
            Set
                Me.cOLOURField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Q_PLANNED() As Decimal
            Get
                Return Me.q_PLANNEDField
            End Get
            Set
                Me.q_PLANNEDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Q_PRODUCED() As Decimal
            Get
                Return Me.q_PRODUCEDField
            End Get
            Set
                Me.q_PRODUCEDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TYPE_BOX() As String
            Get
                Return Me.tYPE_BOXField
            End Get
            Set
                Me.tYPE_BOXField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DATE_BEGIN() As String
            Get
                Return Me.dATE_BEGINField
            End Get
            Set
                Me.dATE_BEGINField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DATE_END() As String
            Get
                Return Me.dATE_ENDField
            End Get
            Set
                Me.dATE_ENDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DATE_BEGIN_REAL() As String
            Get
                Return Me.dATE_BEGIN_REALField
            End Get
            Set
                Me.dATE_BEGIN_REALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DATE_END_REAL() As String
            Get
                Return Me.dATE_END_REALField
            End Get
            Set
                Me.dATE_END_REALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DESCRIPTION_ADD() As String
            Get
                Return Me.dESCRIPTION_ADDField
            End Get
            Set
                Me.dESCRIPTION_ADDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_LIST() As String
            Get
                Return Me.n_LISTField
            End Get
            Set
                Me.n_LISTField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_RIGHE_DOCUM_MOVIMENTAZ
        
        Private n_LISTField As String
        
        Private l_LISTField As String
        
        Private n_ORDER_MFGField As String
        
        Private iTEMField As String
        
        Private cOLOURField As String
        
        Private q_TO_MOVEField As Decimal
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_LIST() As String
            Get
                Return Me.n_LISTField
            End Get
            Set
                Me.n_LISTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property L_LIST() As String
            Get
                Return Me.l_LISTField
            End Get
            Set
                Me.l_LISTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_ORDER_MFG() As String
            Get
                Return Me.n_ORDER_MFGField
            End Get
            Set
                Me.n_ORDER_MFGField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM() As String
            Get
                Return Me.iTEMField
            End Get
            Set
                Me.iTEMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COLOUR() As String
            Get
                Return Me.cOLOURField
            End Get
            Set
                Me.cOLOURField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Q_TO_MOVE() As Decimal
            Get
                Return Me.q_TO_MOVEField
            End Get
            Set
                Me.q_TO_MOVEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_NOTE_ARTICOLO
        
        Private kEY1Field As String
        
        Private kEY2Field As String
        
        Private l_TEXTField As String
        
        Private dATA_TEXTField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property KEY1() As String
            Get
                Return Me.kEY1Field
            End Get
            Set
                Me.kEY1Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property KEY2() As String
            Get
                Return Me.kEY2Field
            End Get
            Set
                Me.kEY2Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property L_TEXT() As String
            Get
                Return Me.l_TEXTField
            End Get
            Set
                Me.l_TEXTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DATA_TEXT() As String
            Get
                Return Me.dATA_TEXTField
            End Get
            Set
                Me.dATA_TEXTField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_MATRICOLE_REALI
        
        Private sERIAL_IDField As String
        
        Private sTATUSField As String
        
        Private iTEMField As String
        
        Private cOLOURField As String
        
        Private n_ORDER_MFGField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SERIAL_ID() As String
            Get
                Return Me.sERIAL_IDField
            End Get
            Set
                Me.sERIAL_IDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property STATUS() As String
            Get
                Return Me.sTATUSField
            End Get
            Set
                Me.sTATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM() As String
            Get
                Return Me.iTEMField
            End Get
            Set
                Me.iTEMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COLOUR() As String
            Get
                Return Me.cOLOURField
            End Get
            Set
                Me.cOLOURField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_ORDER_MFG() As String
            Get
                Return Me.n_ORDER_MFGField
            End Get
            Set
                Me.n_ORDER_MFGField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_MATERIALI_ODP
        
        Private n_ORDER_MFGField As String
        
        Private cOMPONENTField As String
        
        Private cOLUR_COMPField As String
        
        Private q_USEField As Decimal
        
        Private pREFIXField As String
        
        Private sUFFIXField As String
        
        Private oPERATIONField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_ORDER_MFG() As String
            Get
                Return Me.n_ORDER_MFGField
            End Get
            Set
                Me.n_ORDER_MFGField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COMPONENT() As String
            Get
                Return Me.cOMPONENTField
            End Get
            Set
                Me.cOMPONENTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COLUR_COMP() As String
            Get
                Return Me.cOLUR_COMPField
            End Get
            Set
                Me.cOLUR_COMPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Q_USE() As Decimal
            Get
                Return Me.q_USEField
            End Get
            Set
                Me.q_USEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PREFIX() As String
            Get
                Return Me.pREFIXField
            End Get
            Set
                Me.pREFIXField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property SUFFIX() As String
            Get
                Return Me.sUFFIXField
            End Get
            Set
                Me.sUFFIXField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OPERATION() As String
            Get
                Return Me.oPERATIONField
            End Get
            Set
                Me.oPERATIONField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_DESCR_LINGUA
        
        Private iTEMField As String
        
        Private cOLOURField As String
        
        Private lANGUAGEField As String
        
        Private dESCRIPTIONField() As ZMES_TR_TLINE
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM() As String
            Get
                Return Me.iTEMField
            End Get
            Set
                Me.iTEMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COLOUR() As String
            Get
                Return Me.cOLOURField
            End Get
            Set
                Me.cOLOURField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property LANGUAGE() As String
            Get
                Return Me.lANGUAGEField
            End Get
            Set
                Me.lANGUAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property DESCRIPTION() As ZMES_TR_TLINE()
            Get
                Return Me.dESCRIPTIONField
            End Get
            Set
                Me.dESCRIPTIONField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_TLINE
        
        Private tDLINEField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TDLINE() As String
            Get
                Return Me.tDLINEField
            End Get
            Set
                Me.tDLINEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_CYB_PROD
        
        Private oRDINEField As String
        
        Private dATA_IMP_ITALIAField As String
        
        Private dATA_IMP_ESTEROField As String
        
        Private iMP_ITALIAField As String
        
        Private iMP_ESTEROField As String
        
        Private fATTIBILITAField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ORDINE() As String
            Get
                Return Me.oRDINEField
            End Get
            Set
                Me.oRDINEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DATA_IMP_ITALIA() As String
            Get
                Return Me.dATA_IMP_ITALIAField
            End Get
            Set
                Me.dATA_IMP_ITALIAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DATA_IMP_ESTERO() As String
            Get
                Return Me.dATA_IMP_ESTEROField
            End Get
            Set
                Me.dATA_IMP_ESTEROField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IMP_ITALIA() As String
            Get
                Return Me.iMP_ITALIAField
            End Get
            Set
                Me.iMP_ITALIAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property IMP_ESTERO() As String
            Get
                Return Me.iMP_ESTEROField
            End Get
            Set
                Me.iMP_ESTEROField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property FATTIBILITA() As String
            Get
                Return Me.fATTIBILITAField
            End Get
            Set
                Me.fATTIBILITAField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_CICLI_ODP
        
        Private n_ORDER_MFGField As String
        
        Private pARALLEL_WAYField As String
        
        Private oPERATIONField As String
        
        Private aLTERN_WAYField As String
        
        Private aLTERN_PROGRField As String
        
        Private tIME_SETUPField As Decimal
        
        Private tIME_WORKField As Decimal
        
        Private tIME_MAINField As Decimal
        
        Private zPOSITIONField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_ORDER_MFG() As String
            Get
                Return Me.n_ORDER_MFGField
            End Get
            Set
                Me.n_ORDER_MFGField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property PARALLEL_WAY() As String
            Get
                Return Me.pARALLEL_WAYField
            End Get
            Set
                Me.pARALLEL_WAYField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OPERATION() As String
            Get
                Return Me.oPERATIONField
            End Get
            Set
                Me.oPERATIONField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ALTERN_WAY() As String
            Get
                Return Me.aLTERN_WAYField
            End Get
            Set
                Me.aLTERN_WAYField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ALTERN_PROGR() As String
            Get
                Return Me.aLTERN_PROGRField
            End Get
            Set
                Me.aLTERN_PROGRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TIME_SETUP() As Decimal
            Get
                Return Me.tIME_SETUPField
            End Get
            Set
                Me.tIME_SETUPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TIME_WORK() As Decimal
            Get
                Return Me.tIME_WORKField
            End Get
            Set
                Me.tIME_WORKField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TIME_MAIN() As Decimal
            Get
                Return Me.tIME_MAINField
            End Get
            Set
                Me.tIME_MAINField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ZPOSITION() As String
            Get
                Return Me.zPOSITIONField
            End Get
            Set
                Me.zPOSITIONField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_BOLLE_LAVORO
        
        Private n_BILL_WORKField As String
        
        Private sTATUSField As String
        
        Private n_ORDER_MFGField As String
        
        Private dATE_REQUEST_BEGINField As String
        
        Private dATE_REQUEST_ENDField As String
        
        Private q_BOOKEDField As Decimal
        
        Private q_PLANNEDField As Decimal
        
        Private q_PRODUCEDField As Decimal
        
        Private iTEMField As String
        
        Private cOLORField As String
        
        Private oPERATIONField As String
        
        Private tYPE_BOXField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_BILL_WORK() As String
            Get
                Return Me.n_BILL_WORKField
            End Get
            Set
                Me.n_BILL_WORKField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property STATUS() As String
            Get
                Return Me.sTATUSField
            End Get
            Set
                Me.sTATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_ORDER_MFG() As String
            Get
                Return Me.n_ORDER_MFGField
            End Get
            Set
                Me.n_ORDER_MFGField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DATE_REQUEST_BEGIN() As String
            Get
                Return Me.dATE_REQUEST_BEGINField
            End Get
            Set
                Me.dATE_REQUEST_BEGINField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DATE_REQUEST_END() As String
            Get
                Return Me.dATE_REQUEST_ENDField
            End Get
            Set
                Me.dATE_REQUEST_ENDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Q_BOOKED() As Decimal
            Get
                Return Me.q_BOOKEDField
            End Get
            Set
                Me.q_BOOKEDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Q_PLANNED() As Decimal
            Get
                Return Me.q_PLANNEDField
            End Get
            Set
                Me.q_PLANNEDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property Q_PRODUCED() As Decimal
            Get
                Return Me.q_PRODUCEDField
            End Get
            Set
                Me.q_PRODUCEDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM() As String
            Get
                Return Me.iTEMField
            End Get
            Set
                Me.iTEMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COLOR() As String
            Get
                Return Me.cOLORField
            End Get
            Set
                Me.cOLORField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property OPERATION() As String
            Get
                Return Me.oPERATIONField
            End Get
            Set
                Me.oPERATIONField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TYPE_BOX() As String
            Get
                Return Me.tYPE_BOXField
            End Get
            Set
                Me.tYPE_BOXField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_AVANZAMENTO_LISTE_MAG
        
        Private n_LISTField As String
        
        Private n_ORDER_MFGField As String
        
        Private nR_LINES_ACTUALField As Short
        
        Private nR_LINES_CLOSEDField As Short
        
        Private dATE_ISRTField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_LIST() As String
            Get
                Return Me.n_LISTField
            End Get
            Set
                Me.n_LISTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property N_ORDER_MFG() As String
            Get
                Return Me.n_ORDER_MFGField
            End Get
            Set
                Me.n_ORDER_MFGField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NR_LINES_ACTUAL() As Short
            Get
                Return Me.nR_LINES_ACTUALField
            End Get
            Set
                Me.nR_LINES_ACTUALField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property NR_LINES_CLOSED() As Short
            Get
                Return Me.nR_LINES_CLOSEDField
            End Get
            Set
                Me.nR_LINES_CLOSEDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property DATE_ISRT() As String
            Get
                Return Me.dATE_ISRTField
            End Get
            Set
                Me.dATE_ISRTField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_ANAGR_ARTIC_VENDITA
        
        Private iTEMField As String
        
        Private cOLOURField As String
        
        Private cLASS_01Field As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM() As String
            Get
                Return Me.iTEMField
            End Get
            Set
                Me.iTEMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COLOUR() As String
            Get
                Return Me.cOLOURField
            End Get
            Set
                Me.cOLOURField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASS_01() As String
            Get
                Return Me.cLASS_01Field
            End Get
            Set
                Me.cLASS_01Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_ANAGR_ARTIC_DATI_ULTER
        
        Private iTEMField As String
        
        Private cOLOURField As String
        
        Private c_MATCH_CODEField As String
        
        Private vALOREField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM() As String
            Get
                Return Me.iTEMField
            End Get
            Set
                Me.iTEMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COLOUR() As String
            Get
                Return Me.cOLOURField
            End Get
            Set
                Me.cOLOURField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property C_MATCH_CODE() As String
            Get
                Return Me.c_MATCH_CODEField
            End Get
            Set
                Me.c_MATCH_CODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property VALORE() As String
            Get
                Return Me.vALOREField
            End Get
            Set
                Me.vALOREField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_ANAGR_ARTIC_DATI_ACQ
        
        Private iTEMField As String
        
        Private cOLOURField As String
        
        Private tYPE_TESTField As String
        
        Private cLASS_06Field As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM() As String
            Get
                Return Me.iTEMField
            End Get
            Set
                Me.iTEMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COLOUR() As String
            Get
                Return Me.cOLOURField
            End Get
            Set
                Me.cOLOURField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property TYPE_TEST() As String
            Get
                Return Me.tYPE_TESTField
            End Get
            Set
                Me.tYPE_TESTField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASS_06() As String
            Get
                Return Me.cLASS_06Field
            End Get
            Set
                Me.cLASS_06Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_TR_ANAGR_ARTIC
        
        Private iTEMField As String
        
        Private cOLOURField As String
        
        Private dESCRIPTIONField() As ZMES_TR_TLINE
        
        Private sTATUSField As String
        
        Private cLASS_06Field As String
        
        Private mEASURE_UNITField As String
        
        Private cLASS_01Field As String
        
        Private iTEM_REFField As String
        
        Private cLASS_03Field As String
        
        Private bARCODEField As String
        
        Private cLASS_04Field As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM() As String
            Get
                Return Me.iTEMField
            End Get
            Set
                Me.iTEMField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property COLOUR() As String
            Get
                Return Me.cOLOURField
            End Get
            Set
                Me.cOLOURField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property DESCRIPTION() As ZMES_TR_TLINE()
            Get
                Return Me.dESCRIPTIONField
            End Get
            Set
                Me.dESCRIPTIONField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property STATUS() As String
            Get
                Return Me.sTATUSField
            End Get
            Set
                Me.sTATUSField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASS_06() As String
            Get
                Return Me.cLASS_06Field
            End Get
            Set
                Me.cLASS_06Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property MEASURE_UNIT() As String
            Get
                Return Me.mEASURE_UNITField
            End Get
            Set
                Me.mEASURE_UNITField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASS_01() As String
            Get
                Return Me.cLASS_01Field
            End Get
            Set
                Me.cLASS_01Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property ITEM_REF() As String
            Get
                Return Me.iTEM_REFField
            End Get
            Set
                Me.iTEM_REFField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASS_03() As String
            Get
                Return Me.cLASS_03Field
            End Get
            Set
                Me.cLASS_03Field = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property BARCODE() As String
            Get
                Return Me.bARCODEField
            End Get
            Set
                Me.bARCODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property CLASS_04() As String
            Get
                Return Me.cLASS_04Field
            End Get
            Set
                Me.cLASS_04Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="urn:sap-com:document:sap:rfc:functions")>  _
    Partial Public Class ZMES_WS_INResponse
        
        Private e_ANAGR_ARTICField() As ZMES_TR_ANAGR_ARTIC
        
        Private e_ANAGR_ARTIC_DATI_ACQField() As ZMES_TR_ANAGR_ARTIC_DATI_ACQ
        
        Private e_ANAGR_ARTIC_DATI_ULTERField() As ZMES_TR_ANAGR_ARTIC_DATI_ULTER
        
        Private e_ANAGR_ARTIC_VENDITAField() As ZMES_TR_ANAGR_ARTIC_VENDITA
        
        Private e_AVANZAMENTO_LISTE_MAGField() As ZMES_TR_AVANZAMENTO_LISTE_MAG
        
        Private e_BOLLE_LAVOROField() As ZMES_TR_BOLLE_LAVORO
        
        Private e_CICLI_ODPField() As ZMES_TR_CICLI_ODP
        
        Private e_CYB_PRODField() As ZMES_TR_CYB_PROD
        
        Private e_DESCR_LINGUAField() As ZMES_TR_DESCR_LINGUA
        
        Private e_MATERIALI_ODPField() As ZMES_TR_MATERIALI_ODP
        
        Private e_MATRICOLE_REALIField() As ZMES_TR_MATRICOLE_REALI
        
        Private e_MESSAGEField As String
        
        Private e_NOTE_ARTICOLOField() As ZMES_TR_NOTE_ARTICOLO
        
        Private e_RETCODEField As Integer
        
        Private e_RIGHE_DOCUM_MOVIMENTAZIONEField() As ZMES_TR_RIGHE_DOCUM_MOVIMENTAZ
        
        Private e_TESTATA_ODP_INTERNAField() As ZMES_TR_TESTATA_ODP_INTERNA
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_ANAGR_ARTIC() As ZMES_TR_ANAGR_ARTIC()
            Get
                Return Me.e_ANAGR_ARTICField
            End Get
            Set
                Me.e_ANAGR_ARTICField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_ANAGR_ARTIC_DATI_ACQ() As ZMES_TR_ANAGR_ARTIC_DATI_ACQ()
            Get
                Return Me.e_ANAGR_ARTIC_DATI_ACQField
            End Get
            Set
                Me.e_ANAGR_ARTIC_DATI_ACQField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_ANAGR_ARTIC_DATI_ULTER() As ZMES_TR_ANAGR_ARTIC_DATI_ULTER()
            Get
                Return Me.e_ANAGR_ARTIC_DATI_ULTERField
            End Get
            Set
                Me.e_ANAGR_ARTIC_DATI_ULTERField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_ANAGR_ARTIC_VENDITA() As ZMES_TR_ANAGR_ARTIC_VENDITA()
            Get
                Return Me.e_ANAGR_ARTIC_VENDITAField
            End Get
            Set
                Me.e_ANAGR_ARTIC_VENDITAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_AVANZAMENTO_LISTE_MAG() As ZMES_TR_AVANZAMENTO_LISTE_MAG()
            Get
                Return Me.e_AVANZAMENTO_LISTE_MAGField
            End Get
            Set
                Me.e_AVANZAMENTO_LISTE_MAGField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_BOLLE_LAVORO() As ZMES_TR_BOLLE_LAVORO()
            Get
                Return Me.e_BOLLE_LAVOROField
            End Get
            Set
                Me.e_BOLLE_LAVOROField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_CICLI_ODP() As ZMES_TR_CICLI_ODP()
            Get
                Return Me.e_CICLI_ODPField
            End Get
            Set
                Me.e_CICLI_ODPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_CYB_PROD() As ZMES_TR_CYB_PROD()
            Get
                Return Me.e_CYB_PRODField
            End Get
            Set
                Me.e_CYB_PRODField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_DESCR_LINGUA() As ZMES_TR_DESCR_LINGUA()
            Get
                Return Me.e_DESCR_LINGUAField
            End Get
            Set
                Me.e_DESCR_LINGUAField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_MATERIALI_ODP() As ZMES_TR_MATERIALI_ODP()
            Get
                Return Me.e_MATERIALI_ODPField
            End Get
            Set
                Me.e_MATERIALI_ODPField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_MATRICOLE_REALI() As ZMES_TR_MATRICOLE_REALI()
            Get
                Return Me.e_MATRICOLE_REALIField
            End Get
            Set
                Me.e_MATRICOLE_REALIField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property E_MESSAGE() As String
            Get
                Return Me.e_MESSAGEField
            End Get
            Set
                Me.e_MESSAGEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_NOTE_ARTICOLO() As ZMES_TR_NOTE_ARTICOLO()
            Get
                Return Me.e_NOTE_ARTICOLOField
            End Get
            Set
                Me.e_NOTE_ARTICOLOField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property E_RETCODE() As Integer
            Get
                Return Me.e_RETCODEField
            End Get
            Set
                Me.e_RETCODEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_RIGHE_DOCUM_MOVIMENTAZIONE() As ZMES_TR_RIGHE_DOCUM_MOVIMENTAZ()
            Get
                Return Me.e_RIGHE_DOCUM_MOVIMENTAZIONEField
            End Get
            Set
                Me.e_RIGHE_DOCUM_MOVIMENTAZIONEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified),  _
         System.Xml.Serialization.XmlArrayItemAttribute("item", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable:=false)>  _
        Public Property E_TESTATA_ODP_INTERNA() As ZMES_TR_TESTATA_ODP_INTERNA()
            Get
                Return Me.e_TESTATA_ODP_INTERNAField
            End Get
            Set
                Me.e_TESTATA_ODP_INTERNAField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ZMES_WS_INCompletedEventHandler(ByVal sender As Object, ByVal e As ZMES_WS_INCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ZMES_WS_INCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As ZMES_WS_INResponse
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),ZMES_WS_INResponse)
            End Get
        End Property
    End Class
End Namespace
